crate-crypto/go-eth-kzg

- internal/kzg/domain.go
- internal/multiexp/multiexp.go
- internal/utils/utils.go
- internal/utils/utils_test.go
- readme.md
This PR just collects a bunch of minor documentation and readability improvements.
More to follow.
> Minoredits

- internal/kzg/kzg_verify.go
> Typo: Variable rename

- api/api.go
- api/api_test.go
> Add zero point constant

- api/api.go
- api/fiatshamir.go
- api/prove.go
- api/trusted_setup.go
- api/trusted_setup_test.go
- internal/kzg/domain.go
- internal/kzg/fft.go
- internal/kzg/fft_test.go
- internal/kzg/kzg_prove.go
- internal/kzg/kzg_test.go
- internal/kzg/kzg_verify.go
- internal/kzg/srs.go
- internal/kzg/srs_insecure.go
- internal/kzg/srs_test.go
- serialization/serialization.go
This PR collects a lot of minor, mostly documentation-related changes.
Some internal functions have been renamed or changed in how parameters are passed for consistency reasons.
> Minoredits2

- api/api.go
- api/fiatshamir.go
- serialization/serialization_test.go
Just fixes a few minor typos I noticed.
> Fix a few minor typos

- api/api_test.go
- api/bench_test.go
- api/fiatshamir_test.go
- api/trusted_setup_test.go
I think this is a lot cleaner, less verbose.
> Use more testify

- .golangci.yml
- api/api.go
- api/consensus_specs_test.go
- api/trusted_setup.go
- internal/kzg/domain.go
- internal/kzg/domain_test.go
- internal/kzg/fft.go
- internal/kzg/kzg_test.go
- internal/multiexp/multiexp_test.go
- serialization/serialization_test.go
* Move some checks to permanently disabled section.
* Fix some checks & remove them from "maybe fix section".
> Fix some non-controversial findings

- .github/workflows/lint.yml
- .github/workflows/test.yml
* Add matrix of Go versions we should support.
* Rename `go.yml` to `test.yml` (more descriptive).
* Add `push.branches` to `lint.yml` (not actually sure if this is needed).
* Remove quotes around "master" and remove brackets.
> Run CI tests on range of Go versions

- verify.go
Thought this function could use a little love.
> Cleanup parallelized batch verify func

- .github/workflows/test.yml
I don't expect there to be any problems, but we might as well test these just in case.
> Add macOS & Windows to CI tests

- internal/kzg/srs.go
- internal/multiexp/multiexp.go
Nit-picky PR. I think these would look better as one-liners.
> Convert two blocks to one-liners

- consensus_specs_test.go
* Use more `testify`.
* Remove `HexStr` from struct fields.
* I don't think it's very necessary.
*  Remove `assertTestCaseValid` function.
* Replaced with `require.True(t, testCaseValid)`.
* Rename `ProofIsValidPredicate` to `ProofIsValid`.
* I don't think "predicate" is that valuable.
* Add `hexStrToProof` function.
* I think this is clearer than `hexStrToCommitment` + cast.
> Cleanup spec tests

- api.go
- api_test.go
- bench_test.go
- consensus_specs_test.go
- errors.go
- examples_test.go
- internal/multiexp/errors.go
- internal/multiexp/multiexp.go
- internal/multiexp/multiexp_test.go
- prove.go
In reply to https://github.com/crate-crypto/go-kzg-4844/pull/45#issuecomment-1521413166
> Set each method to explicitly take the number of go-routines

- api.go
- fiatshamir.go
- internal/kzg/domain.go
- internal/kzg/kzg_prove.go
- internal/kzg/kzg_verify.go
- internal/multiexp/multiexp.go
- internal/utils/utils.go
- prove.go
- readme.md
- serialization.go
- verify.go
> Updates consensus-spec commits following big endian change

- .golangci.yml
- api.go
- api_eip7594.go
- consensus_specs_test.go
- internal/kzg/domain.go
- internal/kzg/domain_test.go
- internal/kzg/fft.go
- internal/kzg/fft_test.go
- internal/kzg/srs.go
- internal/kzg_multi/kzg_prove.go
- internal/kzg_multi/poly.go
- internal/kzg_multi/poly_test.go
- prove.go
- serialization.go
This adds a naive implementation of ComputeCellsAndKZGProofs
> chore: Add initial ComputeCellsAndKZGProofs method

- api.go
- api_eip7594.go
- consensus_specs_test.go
- errors.go
- internal/kzg/srs.go
- internal/kzg_multi/kzg_verify.go
- internal/kzg_multi/kzg_verify_test.go
- internal/kzg_multi/poly.go
- internal/kzg_multi/poly_test.go
- internal/multiexp/multiexp.go
- internal/multiexp/multiexp_test.go
- serialization.go
This adds a naive implementation of VerifyCellKZGProof
> chore: Add VerifyCellKZGProof

- api_eip7594.go
- consensus_specs_test.go
- errors.go
This adds the intial method to verify a batch of cell proofs
> chore: add InitialVerifyCellKZGProofBatch method

- api.go
- api_eip7594.go
- consensus_specs_test.go
- internal/kzg/domain.go
- internal/kzg_multi/recovery.go
This adds a naive version of RecoverCellsAndComputeKZGProofs method
> chore: Add initial RecoverCellsAndComputeKZGProofs method

- api.go
- internal/erasure_code/erasure_code.go
- internal/erasure_code/erasure_code_test.go
Pulls out the changes from #85 for erasure_code
> chore: Add new erasure_code abstraction

- api_eip7594.go
- errors.go
- internal/kzg_multi/fk20/fk20.go
- internal/kzg_multi/fk20/toeplitz.go
- internal/kzg_multi/kzg_prove.go
- internal/kzg_multi/kzg_prove_test.go
- internal/kzg_multi/kzg_verify.go
- internal/kzg_multi/kzg_verify_test.go
- internal/kzg_multi/srs.go
Pulls out the changes from #85
> chore: Update `kzg_multi` package
