- api/verify.go
- internal/kzg/domain.go
Link to Georges comments are here: https://github.com/asn-d6/go-proto-danksharding-crypto/pull/1
> Nit: Polynomial is not size constrainted, but Blob is. I guess that's fine math-wise, but if that's not useful protocol-wise, I wonder if code could be simplified if the type-system enforces its size.
Since kzg is a generic modular piece of code unrelated to dank-sharding, we allow polynomial to be any size.
> Nit: The way you are passing indexInDomain around seems correct (based on code review), but given that it goes through three different functions and also gets sign-casted, I wonder if we should also do a check here that index < len(p) or something.
If the condition is broken, then we want it to fail by panicking which will happen when it tries to index the polynomial. This would be a …
> Feedback from asn

- internal/kzg/domain.go
- internal/kzg/domain_test.go
- internal/kzg/kzg_test.go
Proposed change: NewDomain should panic if the passed argument is not a power of 2.
I raised a related issue with https://github.com/ethereum/c-kzg-4844/issues/226
The semantics for the case where the domain size is not a power of 2 is not documented; there are multiple options, with the most meaningful being the following: If the domain size m is not a power of 2, polynomials are given as degree m-1-polynomials by their evaluations at g^0, ..., g^m-1; These evaluation points only form a subset of the larger set
g^0, ..., g^M-1, where M is the next power of 2 after M. FFTs operate in the larger space.
The C code tries to achieve this behaviour (well, maybe: While there are some next-power-of-2 calls and careful considerations that seem to achieve this, that case is never tested / …
> Reject domain sizes non power of2

- internal/kzg/domain.go
- internal/kzg/domain_test.go
- internal/kzg/kzg_prove.go
This PR changes some index variables from plain ints to uint64 / int64s.
The reason is that Domain.Cardinality can be up to 2^32, so signed indices could overflow if int is only 32 bits (the Go spec allows int to be either 32 or 64 bits).
Note that this also contains some other commits (duplicated in the other PRs) that would otherwise cause merge conflicts.
I fully expect (harmless) merge conflicts with #12 to happen anyway, so I guess #12 should be resolved first.
> Change `findRootIndex` to use a an int64

- api/api_test.go
- api/bench_test.go
- api/consensus_specs_test.go
- api/examples_test.go
- api/verify.go
To match [the spec](https://github.com/ethereum/consensus-specs/blob/dev/specs/deneb/polynomial-commitments.md#verify_kzg_proof), `proof` should be the last parameter.
> Update VerifyKZGProof params to match spec

- api/api.go
- api/bench_test.go
- api/consensus_specs_test.go
- api/errors.go
- api/examples_test.go
- api/trusted_setup.go
- api/trusted_setup_test.go
- internal/kzg/domain_test.go
- internal/kzg/kzg_prove.go
- internal/kzg/kzg_test.go
- internal/kzg/kzg_verify.go
- internal/kzg/srs_test.go
- internal/multiexp/multiexp_test.go
- internal/utils/utils_test.go
- serialization/serialization.go
- serialization/serialization_test.go
This the codebase according to [`gofumpt -extra`](https://github.com/mvdan/gofumpt).
Eventually, I'll add [`golangci-lint`](https://golangci-lint.run) to enforce this.
> Run gofumpt on everything

- .github/workflows/lint.yml
- .golangci.yml
- internal/kzg/fft.go
Run two pretty common Golang checks:
* [`golangci-lint`](https://golangci-lint.run)
* [`staticcheck`](https://staticcheck.io)
Added `lint.yml` GitHub action which runs these.
Will try to fix findings in the "maybe fix later" section.
> Run golangci-lint & staticcheck in CI

- api/api.go
- api/api_test.go
* Rename variables to better match the [spec](https://github.com/ethereum/consensus-specs/blob/dev/specs/deneb/polynomial-commitments.md#constants).
* I think ZeroPoint is a valid name, but just going with the spec here.
* Also, the linters complained about these being ALL_UPPERCASE.
* Update comments a bit.
* Change from array of decimal integers to hexadecimal.
* Also, wrap (4 lines of 8 bytes).
* Update tests to be a little cleaner.
> Rename global constant to match spec

- .golangci.yml
- internal/utils/utils_test.go
There was one real finding:
```
internal/utils/utils_test.go:116:22: G601: Implicit memory aliasing in for loop. (gosec)
if !expected.Equal(&pow) {
```
This PR fixes it.
As for the other one, we're fine with using `math/rand` so I disabled that check.
> Fix gosec finding

- .golangci.yml
- internal/kzg/kzg_test.go
The `makezero` correctly identified some problems:
```
internal/kzg/kzg_test.go:38:17: append to slice `commitments` with non-zero initialized length (makezero)
commitments = append(commitments, comm)
^
internal/kzg/kzg_test.go:39:12: append to slice `proofs` with non-zero initialized length (makezero)
proofs = append(proofs, proof)
^
internal/kzg/kzg_test.go:47:16: append to slice `commitments` with non-zero initialized length (makezero)
commitments = append(commitments, bls12381.G1Affine{})
^
internal/kzg/kzg_test.go:48:11: append to slice `proofs` with non-zero initialized length (makezero)
proofs = append(proofs, proof)
```
This test was appending commitments/proofs to an array that was already initialized.
> Fix some makezero findings

- .golangci.yml
- api/api_test.go
- api/bench_test.go
- api/examples_test.go
- api/trusted_setup.go
- api/verify.go
- internal/kzg/domain_test.go
- internal/kzg/fft_test.go
- internal/kzg/kzg_prove.go
- internal/kzg/kzg_test.go
- internal/kzg/srs_insecure.go
- internal/kzg/srs_test.go
- internal/multiexp/multiexp_test.go
- internal/utils/utils_test.go
- serialization/serialization_test.go
This PR changes a bunch of variable names (ugh) and uses more testify.
Also, `nosnakecase` is now deprecated and all of the findings are found by `revive`.
> Fix revive/nosnakecase findings

- internal/kzg/domain_test.go
- internal/kzg/kzg_prove.go
- internal/kzg/kzg_test.go
- internal/kzg/srs.go
- internal/kzg/srs_test.go
Where it makes sense to, replace `[]fr.Element` with `Polynomial`.
These are the exact same, but I believe `Polynomial` helps readability.
> Replace []fr.Element with Polynomial in some places

- internal/utils/utils.go
This function is simple enough that it doesn't need a helper function.
> Merge computePowers & ComputePowers

- internal/kzg/domain.go
- internal/kzg/domain_test.go
- internal/kzg/kzg_prove.go
* Add missing `//` in docstring & move sentence to bottom.
* Rename link from `bit_reverse` to `reverse_bits`.
* Add ` - ` to list item.
* Fix a test error message.
* Fix docstring for `Open`.
> Fix some various minor problems

- serialization.go
When I changed this to a group of constants, I didn't know it would affect how the documentation looked. Right now, it looks like this (which I think is pretty ugly):
See: https://pkg.go.dev/github.com/crate-crypto/go-kzg-4844
If you ungroup the constants, it will look like this (rendered locally):
> Ungroup consts in serialization to fix docs

- fiatshamir.go
- internal/kzg/domain.go
- internal/kzg/kzg_prove.go
- internal/kzg/srs_insecure.go
- internal/multiexp/multiexp.go
- internal/utils/utils.go
This converts the remaining markdown links in Go files to Go style.
* From `[link](https://example.com)` to `[link]: https://example.com`.
* Still need to update documentation to use the links in some places.
* I think this should be done in a different PR.
> Convert markdown links in Go files to Go style

- .golangci.yml
- internal/kzg/kzg_verify.go
Found by @jtraglia -- the offending line was ignoring the error. 
It was never caught in tests because the conditions to make an error were always checked for in the section that deserializes and validates Blobs.
> Fix: Returning nil on error

- api.go
- errors.go
- internal/kzg/kzg_prove.go
- internal/kzg/kzg_test.go
- internal/kzg/srs.go
- internal/kzg/srs_test.go
- internal/multiexp/multiexp.go
- internal/multiexp/multiexp_test.go
- prove.go
closes #44 
More context: This sets the number of go routines when committing to a polynomial, ny exposing a way to set the gnark-crypto library parameter.
> Add config parameter to set the number of go routines

- api_test.go
- bench_test.go
- consensus_specs_test.go
- examples_test.go
- fiatshamir.go
- fiatshamir_test.go
- internal/kzg/kzg_prove.go
- prove.go
- serialization.go
- verify.go
This PR does a couple of things. 
First of all, it changes the public interface methods that currently pass `Blob`  by value, to instead pass `*Blob`, that is , by  reference. 
**NOTE**: This means that this PR creates a breaking change, which requires a major version-upgrade of this library, strictly speaking. :warning: 
The `Blob` type is an `array`, of 130K bytes. As opposed to a slice of similar size, when an array is passed by value, every byte is passed over the heap. 
Secondly, this PR pushes this change a bit further into the library, and also spot-fixes some places where memory usage can be reduced. 
This PR on it's own doesn't really make a lot of difference. However, when an external user, e.g. geth, calls this library, the heap-copying might make more of a difference, since …
> Avoid passing large arrays on heap, also use less memory

- api_eip7594.go
- serialization.go
When the skeleton was sketched out, we silenced the linter since some methods and constants were not being used. 
They are now being used, so we can remove these ignore directives
> chore: no longer ignore unused method lints

- api.go
- api_eip7594.go
- internal/kzg_multi/fk20/fk20.go
- internal/kzg_multi/fk20/fk20_test.go
- internal/kzg_multi/fk20/toeplitz.go
- internal/kzg_multi/fk20/toeplitz_test.go
- internal/kzg_multi/kzg_prove.go
- internal/kzg_multi/kzg_prove_test.go
- internal/kzg_multi/poly.go
This replaces the naive method of computing MultiPointProofs with FK20
> chore: use FK20 to generate proofs

- api_eip7594.go
- internal/kzg_multi/poly.go
We have switched to go 1.21, so we can use the slices package where possible to replace common functionality related to slices
> chore: use slices package where possible 

- internal/erasure_code/erasure_code.go
- internal/erasure_code/erasure_code_test.go
- internal/kzg_multi/kzg_prove.go
- internal/kzg_multi/kzg_prove_test.go
- internal/kzg_multi/kzg_verify.go
- internal/kzg_multi/kzg_verify_test.go
- internal/poly/poly.go
- internal/poly/poly_test.go
This pulls out the polynomial changes from #85
> chore: Move polynomial file into its own package

- api.go
- api_eip7594.go
- internal/kzg/kzg.go
- internal/kzg/kzg_prove.go
- internal/kzg/kzg_test.go
- internal/kzg/srs.go
- internal/kzg/srs_test.go
- internal/kzg_multi/errors.go
- internal/kzg_multi/kzg_prove_test.go
- internal/kzg_multi/kzg_verify.go
- internal/kzg_multi/srs.go
- prove.go
- verify.go
> chore: update `kzg` module's abstraction

- api_eip7594.go
- consensus_specs_test.go
> chore: remove verifyCellKzgProof

- internal/poly/poly.go
- internal/poly/poly_test.go
This was pulled out from #85 -- we no longer need lagrangeInterpolate.
> chore: Remove LagrangeInterpolate function

- .github/workflows/lint.yml
- internal/kzg_multi/kzg_verify.go
zkSecurity found a bug in the current code where the proof was not included.
This fixes it while also aligning the behaviour with the 4844 implementation
> fix: Replace Fiat-Shamir with random number generation

- internal/kzg_multi/fk20/toeplitz.go
This came from the zk security audit: The pivot point is a "free-standing" variable so it can be any value, we set it to zero to be consistent with the paper.
> chore: Make Pivot point zero

- api_test.go
- bench_test.go
- consensus_specs_test.go
- examples_test.go
- verify.go
Performance optimization. Allows to avoid copying heavy blobs when the caller uses data structures other than `[]Blob`. Extension of https://github.com/crate-crypto/go-kzg-4844/commit/51e065ee3a14d919c37f3d94ab86f4b5602c608c.
> Pass blobs by pointer to VerifyBlobKZGProofBatch(Par)

- serialization.go
This came from the zk security audit. The function is for unused and is here for fuzzers. If you call it with less than 4096 elements, it will panic.
> chore: check length when calling `SerializePoly`
